apiVersion: v1
kind: LimitRange
metadata:
  name: {{ $.Values.Name }}-default-limit-range
spec:
  limits:
  - default:
    {{ if eq $.Values.Environment "prod" }}
      memory: 4Gi
      cpu: 600m
    defaultRequest:
      memory: 2Gi
      cpu: 300m
    {{ else }}
      memory: 2Gi
      cpu: 300m
    defaultRequest:
      memory: 1Gi
      cpu: 150m
    {{ end }}
    type: Container
