apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.Name }}-binding
subjects:
- kind: ServiceAccount
  name: {{ $.Values.Name }}-sa
roleRef:
  kind: Role
  name: {{ $.Values.Name }}-role
  apiGroup: rbac.authorization.k8s.io
