apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.Name }}-sonoma-svc
  name: {{ $.Values.Name }}-sonoma-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ $.Values.Name }}
  sessionAffinity: None
  type: ClusterIP
