apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.Name }}-case-study-svc
  name: {{ $.Values.Name }}-case-study-svc
  
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ $.Values.Name }}
  sessionAffinity: None
  type: ClusterIP
