version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./front/public:/var/www/html/public"
    ports:
      - "8000:80"
      - "443:443"  
    restart: always
    depends_on:
      - python
    command: ["nginx-debug", "-g", "daemon off;"]
  python:
    build:
      context: .
      dockerfile: ./back/Dockerfile
    volumes:
      - "./back:/var/www/html/app"
    command: /bin/bash -c "uwsgi --ini /var/www/html/app/uwsgi.ini"
  mysql:
    image: mysql
    restart: always
    env_file:
      - ".env"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
