---
- hosts: docker
  become: yes
  tasks:
  - name: Remove docker
    yum:
      name: "{{ item }}"
      state: removed
    with_items:
    - docker
    - docker-client
    - docker-common
    - docker-engine
  - name: install dependencies
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
  - name: Enable Docker Edge & Test repo
    ini_file:
      dest: /etc/yum.repos.d/docer-ce.repo
      section: "{{ item }}"
      option: enabled
      value: 0
    with_items: ['docker-ce-test', 'docker-ce-edge']

  - name: Install Docker and componenets
    package:
      name: "{{item}}"
      state: present
    with_items: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose-plugin']

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes

